name: fall_guardian
description: PSP-aware fall detection and family alert app.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # GPS location
  geolocator: ^10.1.0

  # SMS sending
  flutter_sms: ^3.0.1

  # Local persistence
  shared_preferences: ^2.2.2

  # Local notifications (countdown alert)
  flutter_local_notifications: ^17.0.0

  # UUID for fall event IDs
  uuid: ^4.3.3

  # Date formatting
  intl: ^0.20.2

  # Backend API calls
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
